"""Local Table Migrations

Revision ID: bbf9ce756443
Revises:
Create Date: 2025-07-31 12:10:09.332055

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "bbf9ce756443"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mfa_token",
        sa.Column("phone_number", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("verified", sa.Boolean(), nullable=True),
        sa.Column("code_expires_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("date_created_utc", sa.DateTime(), nullable=True),
        sa.Column("date_updated_utc", sa.DateTime(), nullable=True),
        sa.Column("meta", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "user",
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("phone_number", sa.String(), nullable=True),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("user_type", sa.String(), nullable=False),
        sa.Column("dob", sa.DateTime(), nullable=True),
        sa.Column("gender", sa.String(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("date_created_utc", sa.DateTime(), nullable=True),
        sa.Column("date_updated_utc", sa.DateTime(), nullable=True),
        sa.Column("meta", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("phone_number"),
    )
    op.create_table(
        "user_bio",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("bvn", sa.String(), nullable=True),
        sa.Column("identification", sa.String(), nullable=True),
        sa.Column("address", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("passport", sa.String(), nullable=True),
        sa.Column("signature", sa.String(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("date_created_utc", sa.DateTime(), nullable=True),
        sa.Column("date_updated_utc", sa.DateTime(), nullable=True),
        sa.Column("meta", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_bio")
    op.drop_table("user")
    op.drop_table("mfa_token")
    # ### end Alembic commands ###
